events {}
http {
  resolver 1.1.1.1 8.8.8.8 ipv6=off;
  server {
    listen 80;
    location / {
      set $target https://api.ingham.ai;
      proxy_pass $target;
      proxy_set_header User-Agent "Koch-AI/1.0";
      proxy_set_header Host api.ingham.ai;
      proxy_ssl_server_name on;
    }
  }
}
